config/routes.rb
Rails.application.routes.draw do

  resources :texts
  resources :regexes, defaults: {format: :json}
  devise_for :users
  resources :users

  root 'dashboard#index'

end

app/models/regex.rb
class Regex < ActiveRecord::Base
  belongs_to :user
  belongs_to :text
end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :user
  has_one :regex
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :texts
  has_many :regexs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action {
    @current_page = if params[:controller] == "devise/registrations"
      :signup
    elsif params[:controller] == "devise/sessions"
      :signin
    end
  }
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:username, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
      }
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/regexes_controller.rb
class RegexesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_regex, only: [:show, :edit, :update, :destroy]

  # GET /regexes
  # GET /regexes.json
  def index
    @regexes = Regex.where(user: current_user)
  end

  # GET /regexes/1
  # GET /regexes/1.json
  def show
  end

  # GET /regexes/new
  def new
    @regex = Regex.new
  end

  # GET /regexes/1/edit
  def edit
  end

  # POST /regexes
  # POST /regexes.json
  def create
    @regex = Regex.new(regex_params)
    #current_user.regexes << @regex

    respond_to do |format|
      if @regex.save
        format.html { redirect_to @regex, notice: 'Regex was successfully created.' }
        format.json { render :show, status: :created, location: @regex }
      else
        format.html { render :new }
        format.json { render json: @regex.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regexes/1
  # PATCH/PUT /regexes/1.json
  def update
    respond_to do |format|
      if @regex.update(regex_params)
        format.html { redirect_to @regex, notice: 'Regex was successfully updated.' }
        format.json { render :show, status: :ok, location: @regex }
      else
        format.html { render :edit }
        format.json { render json: @regex.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regexes/1
  # DELETE /regexes/1.json
  def destroy
    @regex.destroy
    respond_to do |format|
      format.html { redirect_to regexes_url, notice: 'Regex was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regex
      @regex = Regex.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regex_params
      params.require(:regex).permit(:expression, :title, :user_id, :text_id)
    end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_text, only: [:show, :edit, :update, :destroy]

  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = Text.new
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: 'Text was successfully created.' }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:plaintext, :code, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/regexes_helper.rb
module RegexesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-xs-2 col-lg-2 col-sm-2">
      <!--Sidebar content-->
      <div>Saved Expressions:</div>
      <span id="regexs"></span>
      <script id="regex-template" type="text/template">
        {{ if( _.size(regexs) > 0 ){ }}
          {{ regexs.forEach( function(regex){ }}
            <div><a class="link" cid="{{= regex.cid }}">{{= regex.expression  }}</a><span cid="{{= regex.cid }}" class="link glyphicon glyphicon-remove" aria-hidden="true"></span></div>
          {{  });  }}
        {{ } else {   }}
          <div class="placeholder">No saved expressions</div>
        {{ } }}
      </script>
    </div>
    <div class="col-xs-10 col-lg-10 col-sm-10">
      <div class="panel panel-default">
        <div class="panel-body">
          <section id="text-section">
            <strong>Search Results (found matches are highlighted)</strong>
            <div class="panel panel-default">
              <div class="panel-body search-results">
              </div>
            </div>
            <div class="form-group">
              <label>Enter text to be searched here</label>
              <textarea class="form-control" rows="3"></textarea>
            </div>
          </section>
          <section id="regex-input-section">
            <div class="form-group">
              <label>Enter regular expression to match with text above</label>
              <input id="regex-input" type="text" class="form-control">
            </div>
            <div class="form-group">
              <input id="regex-btn" class="btn btn-default" type="button" value="Save">
            </div>
          </section>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Regex Ninja</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="<%= root_path %>">
            Regex Ninja
          </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              Welcome <%= current_user.username %> |
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <li <% if @current_page == :signin %> class="active"<% end %> ><%= link_to "Sign in", new_user_session_path %></li>
              <li <% if @current_page == :signup %> class="active"<% end %> ><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/regexes/_form.html.erb
<%= form_for(@regex) do |f| %>
  <% if @regex.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@regex.errors.count, "error") %> prohibited this regex from being saved:</h2>

      <ul>
      <% @regex.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expression %><br>
    <%= f.text_field :expression %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :text_id %><br>
    <%= f.text_field :text_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regexes/edit.html.erb
<h1>Editing Regex</h1>

<%= render 'form' %>

<%= link_to 'Show', @regex %> |
<%= link_to 'Back', regexes_path %>

app/views/regexes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Regexes</h1>

<table>
  <thead>
    <tr>
      <th>Expression</th>
      <th>Title</th>
      <th>User</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regexes.each do |regex| %>
      <tr>
        <td><%= regex.expression %></td>
        <td><%= regex.title %></td>
        <td><%= regex.user %></td>
        <td><%= regex.text %></td>
        <td><%= link_to 'Show', regex %></td>
        <td><%= link_to 'Edit', edit_regex_path(regex) %></td>
        <td><%= link_to 'Destroy', regex, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Regex', new_regex_path %>

app/views/regexes/new.html.erb
<h1>New Regex</h1>

<%= render 'form' %>

<%= link_to 'Back', regexes_path %>

app/views/regexes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expression:</strong>
  <%= @regex.expression %>
</p>

<p>
  <strong>Title:</strong>
  <%= @regex.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @regex.user %>
</p>

<p>
  <strong>Text:</strong>
  <%= @regex.text %>
</p>

<%= link_to 'Edit', edit_regex_path(@regex) %> |
<%= link_to 'Back', regexes_path %>

app/views/texts/_form.html.erb
<%= form_for(@text) do |f| %>
  <% if @text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% @text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plaintext %><br>
    <%= f.text_field :plaintext %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form' %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Texts</h1>

<table>
  <thead>
    <tr>
      <th>Plaintext</th>
      <th>Code</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @texts.each do |text| %>
      <tr>
        <td><%= text.plaintext %></td>
        <td><%= text.code %></td>
        <td><%= text.user %></td>
        <td><%= link_to 'Show', text %></td>
        <td><%= link_to 'Edit', edit_text_path(text) %></td>
        <td><%= link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text', new_text_path %>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form' %>

<%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plaintext:</strong>
  <%= @text.plaintext %>
</p>

<p>
  <strong>Code:</strong>
  <%= @text.code %>
</p>

<p>
  <strong>User:</strong>
  <%= @text.user %>
</p>

<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>